[project]
name="lana_lyric_analysis"
version="1.0.0"
requires-python=">=3.11.0"
dependencies =[
    "jupyter",
    "matplotlib",
    "nltk",
    "numpy",
    "pandas",
    "seaborn",
    "scikit-learn",
    "wordcloud"
]

[pyproject.optional-dependencies]
dev = [
    "pytest"
]

[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]

build-backend="setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]